openapi: 3.0.0
info:
  title: IdeaSoft
  version: 1.0.0
servers:
  - url: http://{{apiurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Orders
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Ümit UZ
                email: umituz9999@gmail.com
                password: '123456789'
                password_confirmation: '123456789'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: umituz998@gmail.com
                password: '123456789'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - Orders
      summary: Get Order List
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Orders
      summary: Create New Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                customer_id: 1
                items:
                  - product_id: 1
                    quantity: 2
                    unit_price: '49.50'
                    total: '99.00'
                  - product_id: 2
                    quantity: 1
                    unit_price: '120.75'
                    total: '120.75'
                total: '219.75'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Show Order Details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Orders
      summary: Delete Order
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}/discounts:
    get:
      tags:
        - Orders
      summary: Apply Discount to Order
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
